"""
voice_client.py
Local Python client for Kin-ai-avatar to connect to the Google Colab OpenVoice server.
Provides both full-audio synthesis and streaming sentence-by-sentence synthesis.
"""

import os
import re
import requests
from pathlib import Path
from typing import Generator, Optional

class ColabVoiceClient:
    def __init__(self, colab_url: Optional[str] = None):
        """
        :param colab_url: The ngrok or localtunnel URL generated by your Google Colab notebook.
                          e.g. "https://xxxx-xx-xx-xx.ngrok-free.app"
        """
        self.colab_url = (colab_url or os.getenv("COLAB_VOICE_URL", "")).rstrip("/")
        if not self.colab_url:
            print("[Warning] COLAB_VOICE_URL is not set. Set it before calling synthesis endpoints.")

    def set_url(self, url: str):
        self.colab_url = url.rstrip("/")

    def check_health(self) -> dict:
        """Verify the Colab server is live and running on GPU."""
        if not self.colab_url:
            return {"status": "error", "message": "Colab URL not configured"}
        try:
            r = requests.get(f"{self.colab_url}/health", timeout=5)
            return r.json()
        except Exception as e:
            return {"status": "error", "message": str(e)}

    def register_voice_sample(self, speaker_name: str, audio_path: str) -> dict:
        """
        Uploads a reference voice sample (WAV/MP3) to Colab to extract and cache its tone color.
        """
        if not os.path.exists(audio_path):
            raise FileNotFoundError(f"Audio file not found: {audio_path}")

        url = f"{self.colab_url}/register_voice"
        with open(audio_path, "rb") as f:
            files = {"file": (os.path.basename(audio_path), f, "audio/wav")}
            data = {"name": speaker_name}
            resp = requests.post(url, data=data, files=files)
            resp.raise_for_status()
            return resp.json()

    def synthesize(self, text: str, speaker_name: str = "elder", accent: str = "en-us", speed: float = 1.0) -> bytes:
        """
        Synthesize text with cloned voice. Returns raw WAV bytes.
        """
        url = f"{self.colab_url}/synthesize"
        payload = {
            "text": text,
            "speaker_name": speaker_name,
            "accent": accent,
            "speed": speed
        }
        resp = requests.post(url, json=payload, timeout=30)
        resp.raise_for_status()
        return resp.content

    def synthesize_to_file(self, text: str, output_path: str, speaker_name: str = "elder", **kwargs):
        """Generates audio and writes directly to an output file."""
        wav_bytes = self.synthesize(text, speaker_name=speaker_name, **kwargs)
        with open(output_path, "wb") as f:
            f.write(wav_bytes)
        return output_path

    def stream_sentences(
        self,
        token_generator: Generator[str, None, None],
        speaker_name: str = "elder",
        accent: str = "en-us"
    ) -> Generator[bytes, None, None]:
        """
        Takes a streaming token generator (e.g. from Clonellm's engine.ask_stream())
        splits into complete clauses/sentences, and yields WAV audio bytes as each sentence completes.
        This provides sub-second streaming playback!
        """
        sentence_endings = re.compile(r'([.!?]+)')
        buffer = ""

        for token in token_generator:
            buffer += token
            parts = sentence_endings.split(buffer)
            if len(parts) > 2:
                complete_sentence = parts[0] + parts[1]
                buffer = "".join(parts[2:])

                if complete_sentence.strip():
                    try:
                        audio_bytes = self.synthesize(
                            text=complete_sentence.strip(),
                            speaker_name=speaker_name,
                            accent=accent
                        )
                        yield audio_bytes
                    except Exception as e:
                        print(f"[Streaming Voice Error] {e}")

        # Flush remaining text
        if buffer.strip():
            try:
                audio_bytes = self.synthesize(
                    text=buffer.strip(),
                    speaker_name=speaker_name,
                    accent=accent
                )
                yield audio_bytes
            except Exception as e:
                print(f"[Streaming Voice Error] {e}")


if __name__ == "__main__":
    # Example usage:
    # Set your Colab ngrok URL here:
    TEST_COLAB_URL = "https://your-ngrok-id.ngrok-free.app"
    client = ColabVoiceClient(TEST_COLAB_URL)
    print("Colab Health:", client.check_health())
